### ISSUE TITLE
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

### ISSUE THREAD

**Issue by ApoorvaSuresh** [dimitymiller/openset_detection#2]
I get this error while training Faster RCNN on Pascal VOC dataset. Created the conda environment as suggested using the yml file (uses python 3.7) and all other packages are intact. 
Could you please let me know how to solve this issue?

Thanks in advance :)

**Comment by dimitymiller** [comment]
Thanks for flagging! I need more details to help resolve this. Can you please share the full terminal error (from the line that runs the file all the way to the bottom of the error)?

**Comment by ApoorvaSuresh** [comment]
Thank you for your reply! Here is the error:

```
/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimentalfeature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "tools/train_custom.py", line 199, in <module>
    main()
  File "tools/train_custom.py", line 195, in main
    meta=meta)
  File "/home/ubuntu/openset_det/mmdetection/mmdet/apis/train.py", line 172, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ubuntu/openset_det/mmdetection/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/openset_det/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/ubuntu/openset_det/mmdetection/mmdet/models/detectors/two_stage.py", line 135, in forward_train
    proposal_cfg=proposal_cfg)
  File "/home/ubuntu/openset_det/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 58, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/openset_det/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 580, in get_bboxes
    scale_factors, cfg, rescale)
  File "/home/ubuntu/openset_det/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 186, in _get_bboxes
    cfg.nms)
  File "/home/ubuntu/miniconda3/envs/os_mmdet/lib/python3.7/site-packages/mmcv/ops/nms.py", line 297, in batched_nms
    max_coordinate = boxes.max()
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
```

**Comment by dimitymiller** [comment]
Can you pull the latest commit and run again to see if you still get the issue?

There was a very low batch-size in the config file for Pascal VOC-OS which may have led to the error. Seems to be working now on my machine.

**Comment by ApoorvaSuresh** [comment]
Hi again :)
Thank you very much for the quick assistance on this! I'm able to successfully train now. I shall close this issue :)
Best,
Apoorva

**Comment by ApoorvaSuresh** [comment]
I realized that the training works only with certain specific parameters in mmdetection\configs\_base_\models\faster_rcnn_r50_fpn_voc_wAnchor.py (with very low iou values set). Also, it is not fool-proof. The first time, the training completed successfully, but I am trying to redo the training with the same config- it fails. I'm trying to perform the same training again with various combinations of ious, and it fails everytime.
```
train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.1,         #here   0.7, 0.3, 0.3
                neg_iou_thr=0.0,
                min_pos_iou=0.0,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.1), #here 0.7
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.3,           #here 0.5, 0.5, 0.5
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
```

**Comment by dimitymiller** [comment]
It's unclear whether this is an issue introduced by our Anchor loss, or whether it's an instability in the training of Faster R-CNN.

My recommendation would be to try training a standard cross-entropy Faster R-CNN with these new parameters, to see if that's stable. If so, then try re-training with Anchor loss but be prepared to play with the hyper-parameters, specifically the one that weights the Anchor loss. You may need to train for a few epochs with just cross-entropy loss, then add in the Anchor loss once it is stable.

In the paper, we used the Faster R-CNN parameters that can be found in the original config. I hope you can get it working for what you need, but going to close this issue now as it's outside the scope of the paper that this code supports.
